// 图书分类 sidebar 工厂：外层 category 提供分类标题和面包屑，
// 内层 autogenerated 按目录自动收集书籍文档。
const bookCategory = (label, dir) => [
  {
    type: 'category',
    label,
    collapsible: false,
    items: [{ type: 'autogenerated', dirName: `books/${dir}` }],
  },
];

module.exports = {
  General: [
    'general/todo',
    'general/dom',
    'general/network',
    'general/https',
    'general/cache',
    'general/performance',
    'general/security',
  ],
  JavaScript: [
    'javascript/basic',
    'javascript/array',
    'javascript/object',
    'javascript/destruct',
    'javascript/event-loop',
    'javascript/memory',
    'javascript/regex',
    'javascript/module',
    {
      snippets: [
        'javascript/snippets/conditional',
        'javascript/snippets/functions',
        'javascript/snippets/animation',
      ],
    },
  ],
  TypeScript: [
    'typescript/basic',
    'typescript/covariant',
    'typescript/type-operation',
  ],

  CSS: [
    'css/basic',
    'css/blank',
    'css/margin',
    'css/animation',
    {
      snippets: ['css/snippets/tricks'],
    },
  ],
  Library: [
    'library/nx',
    'library/node',
    'library/hapi',
    'library/sequelize',
    {
      React: [
        'library/react/basic',
        'library/react/react-performance',
        'library/react/render',
        'library/react/conditional-rendering',
        'library/react/diff',
        'library/react/life-circle',
        'library/react/patterns',
        'library/react/fiber',
        'library/react/useImperativeHandle',
        'library/react/react-router',
        'library/react/redux-observable',
      ],
      Vue: ['library/vue/deep-selector'],
    },
  ],

  Database: [
    {
      MySQL: [
        'data/db/install-on-mac',
        'data/db/dump',
        'data/db/table',
        'data/db/data-type',
        'data/db/select',
        'data/db/update',
        'data/db/delete',
        'data/db/join',
      ],
    },
    'data/db/postgreSQL',
  ],

  Python: [
    'data/python/env',
    'data/python/sql-alchemy',
    'data/python/sql-alchemy-relationship',
  ],

  tools: {
    Shell: [
      'tools/shell/commands',
      'tools/shell/proxy',
      'tools/shell/npm',
      'tools/shell/shell-script',
      'tools/shell/tmux',
      'tools/shell/git',
      'tools/shell/grep',
      'tools/shell/awk',
      'tools/shell/uniq',
      'tools/shell/ffmpeg',
    ],
    Mac: [
      'tools/mac/system',
      'tools/mac/terminal',
      'tools/mac/software',
      'tools/mac/skills',
      'tools/mac/alfred',
    ],
    Ubuntu: [
      'tools/ubuntu/ubuntu',
      'tools/ubuntu/wsl',
      'tools/ubuntu/operation',
    ],
    Tools: [
      'tools/tools/vscode',
      'tools/tools/webstorm',
      'tools/tools/chrome',
      'tools/tools/Mermaid',
    ],

    软技能: [
      'tools/soft/delay',
      'tools/soft/team-work',
      'tools/soft/subjective',
    ],
  },
  algorithm: {
    字符串: ['algorithm/string/substring_search'],
    树: ['algorithm/tree/traverse'],
    图: [
      'algorithm/graphs/union-find',
      'algorithm/graphs/bellman-ford',
      'algorithm/graphs/dijkstra',
    ],
    应用: [
      'algorithm/application/binary-search',
      'algorithm/application/double-pointer',
      'algorithm/application/fibonacci',
      'algorithm/application/dutch-flag',
      'algorithm/application/leetcode-hot-300',
    ],
  },
  // 每个图书分类一个独立 sidebar：阅读某本书时，侧栏只显示该分类的书。
  // 目录内容由 autogenerated 自动生成，新增书籍只需把 md 文件放进对应目录。
  booksParenting: bookCategory('育儿', 'parenting'),
  booksHealth: bookCategory('健康', 'health'),
  booksMethodology: bookCategory('工作方法论', 'methodology'),
  booksProductivity: bookCategory('效率', 'productivity'),
  booksHistory: bookCategory('历史', 'history'),
  booksBiography: bookCategory('人物传记', 'biography'),
  booksPsychology: bookCategory('心理学', 'psychology'),
  booksSociology: bookCategory('社会学', 'sociology'),
  booksScience: bookCategory('科学技术', 'science'),
  booksPhilosophy: bookCategory('哲学', 'philosophy'),
  booksEssay: bookCategory('杂文', 'essay'),
  booksGeography: bookCategory('地理', 'geography'),
  booksPoem: bookCategory('诗歌', 'poem'),
  booksNovel: bookCategory('小说', 'novel'),
};
